eureka:
  client: 
    registry-fetch-interval-seconds: 30 #拉取服务注册信息时间，默认60s
  instance:
    instanceId: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
    status-page-url-path: /actuator/info
    health-check-url-path: /actuator/health
    instance-id: ${spring.application.name}:${random.int[19000,19999]}
    statusPageUrlPath: /hystrix
    #Eureka客户端向服务端发送心跳的时间间隔，单位为秒
    lease-renewal-interval-in-seconds: 30
    #Eureka服务端在收到最后一次心跳之后等待的过期时间上限，单位为秒。
    #超过该时间没有收到心跳，则服务端会将该服务实例从服务清单中剔除，从而禁止服务调用请求被发送到该实例上
    lease-expiration-duration-in-seconds: 90
    prefer-ip-address: true
management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS